-- 1. Create Database and Schema 
CREATE DATABASE IF NOT EXISTS "SAAS_SUBSCRIPTION";

USE DATABASE "SAAS_SUBSCRIPTION";

CREATE SCHEMA IF NOT EXISTS PUBLIC;

USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_WH;

-- 2. Create ACCOUNTS table
CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    ACCOUNT_NAME VARCHAR,
    INDUSTRY VARCHAR,
    COUNTRY VARCHAR,
    SIGNUP_DATE VARCHAR, 
    REFERRAL_SOURCE VARCHAR,
    PLAN_TIER VARCHAR,
    SEATS NUMBER,
    IS_TRIAL BOOLEAN,
    CHURN_FLAG BOOLEAN
);

-- 3. Create CHURN_EVENTS table
CREATE TABLE IF NOT EXISTS CHURN_EVENTS (
    CHURN_EVENT_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CHURN_DATE VARCHAR,
    REASON_CODE VARCHAR,
    REFUND_AMOUNT_USD FLOAT,
    PRECEDING_UPGRADE_FLAG BOOLEAN,
    PRECEDING_DOWNGRADE_FLAG BOOLEAN,
    IS_REACTIVATION BOOLEAN,
    FEEDBACK_TEXT VARCHAR
);


-- 4. Create FEATURE_USAGE table
CREATE TABLE IF NOT EXISTS FEATURE_USAGE (
    USAGE_ID VARCHAR,
    SUBSCRIPTION_ID VARCHAR,
    USAGE_DATE VARCHAR,
    FEATURE_NAME VARCHAR,
    USAGE_COUNT NUMBER,
    USAGE_DURATION_SECS NUMBER,
    ERROR_COUNT NUMBER,
    IS_BETA_FEATURE BOOLEAN
);

-- 5. Create SUBSCRIPTIONS table
CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (
    SUBSCRIPTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    START_DATE VARCHAR,
    END_DATE VARCHAR,
    PLAN_TIER VARCHAR,
    SEATS NUMBER,
    MRR_AMOUNT FLOAT,
    ARR_AMOUNT FLOAT,
    IS_TRIAL BOOLEAN,
    UPGRADE_FLAG BOOLEAN,
    DOWNGRADE_FLAG BOOLEAN,
    CHURN_FLAG BOOLEAN,
    BILLING_FREQUENCY VARCHAR,
    AUTO_RENEW_FLAG BOOLEAN
);

-- 6. Create SUPPORT_TICKETS table
CREATE TABLE IF NOT EXISTS SUPPORT_TICKETS (
    TICKET_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    SUBMITTED_AT VARCHAR,
    CLOSED_AT VARCHAR,
    RESOLUTION_TIME_HOURS FLOAT,
    PRIORITY VARCHAR,
    FIRST_RESPONSE_TIME_MINS NUMBER,
    SATISFACTION_SCORE NUMBER,
    ESCALATION_FLAG BOOLEAN
);