-- 1. Set the context (Always use quotes for DB with spaces)
USE DATABASE "SAAS_SUBSCRIPTION";
USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_WH;


-- 2. Copy Data Into RAW_ACCOUNTS
COPY INTO ACCOUNTS
FROM @RAW_DATA_STAGE/ravenstack_accounts.csv
FILE_FORMAT = (
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';


-- 3. Copy Data Into RAW_CHURN_EVENTS
COPY INTO CHURN_EVENTS
FROM @RAW_DATA_STAGE/ravenstack_churn_events.csv
FILE_FORMAT = (
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';


-- 4. Copy Data Into RAW_FEATURE_USAGE
COPY INTO FEATURE_USAGE
FROM @RAW_DATA_STAGE/ravenstack_feature_usage.csv
FILE_FORMAT = (
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';


-- 5. Copy Data Into RAW_SUBSCRIPTIONS
COPY INTO SUBSCRIPTIONS
FROM @RAW_DATA_STAGE/ravenstack_subscriptions.csv
FILE_FORMAT = (
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';


-- 6. Copy Data Into RAW_SUPPORT_TICKETS
COPY INTO SUPPORT_TICKETS
FROM @RAW_DATA_STAGE/ravenstack_support_tickets.csv
FILE_FORMAT = (
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';